variables:
  PROJ_NAME: "streamlit-template"
  REPO_NAME: "dgis-prs-std-docker-local"

stages:
  - build

docker-job:
  stage: build
  image: 
    name: artifactory.sofa.dev/gcr-remote/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"artifactory.sofa.dev\":{\"username\":\"$ARTIFACTORY_USER\",\"password\":\"$ARTIFACTORY_PASS\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --single-snapshot --destination artifactory.sofa.dev/$REPO_NAME/$PROJ_NAME:$CI_COMMIT_SHORT_SHA
