stages:
  - build
#  - test

build-code-job:
  stage: build
  script:
    - echo "Check the ruby version, then build some Ruby project files:"

build-docker-image-job:
  stage: build
  image: 
    name: artifactory.sofa.dev/gcr-remote/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"artifactory.sofa.dev\":{\"username\":\"$ARTIFACTORY_USER\",\"password\":\"$ARTIFACTORY_PASS\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --single-snapshot --destination artifactory.sofa.dev/your-docker-local/your-image-name:$CI_COMMIT_SHORT_SHA

# test-code-job1:
#   stage: test
#   script:
#     - echo "If the files are built successfully, test some files with one command:"
#     - rake test1

# test-code-job2:
#   stage: test
#   script:
#     - echo "If the files are built successfully, test other files with a different command:"
#     - rake test2
