apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
# data:
#   openai_api_key: "{{ .Values.openai.api_key }}"
#   azure_openai_api_key: "{{ .Values.openai.api_key }}"
